type = "webpack"
account_id = ""
zone_id = "9258b29d3b22bdba0666469e82d18225"
workers_dev = true

[env.development]
name = "solidjs-dev"
route = "dev.solidjs.com/*"

[env.production]
name = "solidjs"
route = "www.solidjs.com/*"

[site]
bucket = "./dist"
entry-point = "workers-site"
